---
title: "US Tilapia Imports"
author: "Desik Somasundaram"
date: "8/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(skimr)
```

## Read in Data

```{r}
us_tilapia_imports <- read_csv(here("data", "us_tilapia_imports.csv"))
```
# Explore the data

```{r}
summary(us_tilapia_imports)

names(us_tilapia_imports)

dim(us_tilapia_imports)

skim(us_tilapia_imports)
```
```{r}
reshaped_us_til_imports <- pivot_longer(data = us_tilapia_imports, cols = !country, names_to = "year")

class(reshaped_us_til_imports$year)

reshaped_us_til_imports <-mutate(reshaped_us_til_imports, year = as.numeric(year))

class(reshaped_us_til_imports$year)
```
```{r}

yearly_tilapia_tot <- reshaped_us_til_imports %>% 
  dplyr::group_by(year) %>% 
  summarize(value = sum(value, na.rm = TRUE))

yearly_tilapia_tot_plot <- ggplot(data = yearly_tilapia_tot, aes(x = year, y = value)) + geom_line() + labs(title = "Total US Tilapia Imports by Year") + xlab("Year") + ylab("Tilapia Imports Total Weights (in thousands of pounds)")

yearly_tilapia_tot_plot

ggsave(here("figs", "yearly_tilapia_tot_plot.png"), yearly_tilapia_tot_plot)
```
## Subset of Ecuador, Honduras, Costa Rica and Mexico

```{r}

countries_subset <- c("Ecuador", "Honduras", "Costa Rica", "Mexico")

subset_yearly_tilapia_tot <- reshaped_us_til_imports %>% 
  dplyr::filter(country %in% countries_subset) %>% 
  dplyr::group_by(year) %>% 
  summarize(value = sum(value, na.rm = TRUE))

subset_yearly_tilapia_tot_plot <- ggplot(data = subset_yearly_tilapia_tot, aes(x = year, y = value)) + geom_line() + labs(title = "US Tilapia Imports by Year from Ecuador, Honduras, Costa Rica and Mexico") + xlab("Year") + ylab("Tilapia Imports Total Weights (in thousands of pounds)")

subset_yearly_tilapia_tot_plot

ggsave(here("figs", "subset_yearly_tilapia_tot_plot.png"), subset_yearly_tilapia_tot_plot)
```

